#!/bin/sh

if [ -f "debian/control.in" ]; then
    PATH="debian"
elif [ -f "./control.in" ]; then
    PATH="."
else
    echo "Error control.in not found" 1>&2
    exit 1
fi

echo "#WARNING: autogenerated control please use ./debian/gen-default-control.sh (see control.in)" > ${PATH}/control
/bin/sed -e 's/^#JAVA#//' < ${PATH}/control.in >> ${PATH}/control
