/* lasso/lasso_config.h.  Generated by configure.  */
/* lasso/lasso_config.h.in.  Generated from configure.ac by autoheader.  */

/* Define if check available with XML support */
/* #undef CHECK_IS_XML */

/* Define to 1 if you have the <dlfcn.h> header file. */
/* #undef HAVE_DLFCN_H */

/* Define to 1 if you have the <inttypes.h> header file. */
/* #undef HAVE_INTTYPES_H */

/* Define to 1 if you have the <jni.h> header file. */
/* #undef HAVE_JNI_H */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
/* #define HAVE_STDINT_H */

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
/* #undef HAVE_STRINGS_H */

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
/* #undef HAVE_UNISTD_H */

/* Release version as a decimal */
#define LASSO_VERSION_DECIMAL 600

/* Major version number */
#define LASSO_VERSION_MAJOR 0

/* Minor version number */
#define LASSO_VERSION_MINOR 6

/* Release version number */
#define LASSO_VERSION_SUBMINOR 0

/* Windows version of the lasso version */
#define LASSO_WINDOWS_VERSION 0,6,0,0

/* Define if ID-WSF support is enabled */
/* #undef LASSO_WSF_ENABLED */

/* Define to 1 if your C compiler doesn't accept -c and -o together. */
/* #undef NO_MINUS_C_MINUS_O */

/* Name of package */
#define PACKAGE "lasso"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "lasso-devel@lists.labs.libre-entreprise.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "Liberty Alliance Single Sign On"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "Liberty Alliance Single Sign On 0.6.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "liberty-alliance-single-sign-on"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.6.0"

/* Define to 1 if the C compiler supports function prototypes. */
#define PROTOTYPES 1

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.6.0"

/* Define like PROTOTYPES; this can be used by system headers. */
#define __PROTOTYPES 1
