%{
#include <lasso/xml/id-wsf-2.0/sb2_sender.h>
#include <lasso/xml/id-wsf-2.0/sb2_consent.h>
#include <lasso/xml/id-wsf-2.0/sb2_redirect_request.h>
#include <lasso/xml/id-wsf-2.0/sb2_user_interaction_header.h>
#include <lasso/xml/id-wsf-2.0/sb2_usage_directive.h>
#include <lasso/xml/id-wsf-2.0/sb2_target_identity.h>
#include <lasso/xml/id-wsf-2.0/sb2_timeout.h>
#include <lasso/xml/id-wsf-2.0/sb2_credentials_context.h>
#include <lasso/xml/id-wsf-2.0/ps_object.h>
#include <lasso/xml/id-wsf-2.0/ps_request_abstract.h>
#include <lasso/xml/id-wsf-2.0/ps_test_membership_request.h>
#include <lasso/xml/id-wsf-2.0/ps_remove_entity_request.h>
#include <lasso/xml/id-wsf-2.0/ps_add_to_collection_request.h>
#include <lasso/xml/id-wsf-2.0/ps_remove_collection_request.h>
#include <lasso/xml/id-wsf-2.0/ps_add_known_entity_request.h>
#include <lasso/xml/id-wsf-2.0/ps_add_entity_request.h>
#include <lasso/xml/id-wsf-2.0/ps_remove_from_collection_request.h>
#include <lasso/xml/id-wsf-2.0/ps_list_members_request.h>
#include <lasso/xml/id-wsf-2.0/ps_query_objects_request.h>
#include <lasso/xml/id-wsf-2.0/ps_set_object_info_request.h>
#include <lasso/xml/id-wsf-2.0/ps_get_object_info_request.h>
#include <lasso/xml/id-wsf-2.0/ps_item_data.h>
#include <lasso/xml/id-wsf-2.0/ps_response_abstract.h>
#include <lasso/xml/id-wsf-2.0/ps_add_known_entity_response.h>
#include <lasso/xml/id-wsf-2.0/ps_add_entity_response.h>
#include <lasso/xml/id-wsf-2.0/ps_add_collection_response.h>
#include <lasso/xml/id-wsf-2.0/ps_query_objects_response.h>
#include <lasso/xml/id-wsf-2.0/ps_list_members_response.h>
#include <lasso/xml/id-wsf-2.0/ps_get_object_info_response.h>
#include <lasso/xml/id-wsf-2.0/ps_resolve_identifier_response.h>
#include <lasso/xml/id-wsf-2.0/ps_resolve_identifier_request.h>
#include <lasso/xml/id-wsf-2.0/ps_test_membership_response.h>
#include <lasso/xml/id-wsf-2.0/ps_add_collection_request.h>
#include <lasso/xml/id-wsf-2.0/ps_notify.h>
#include <lasso/xml/id-wsf-2.0/subsref_app_data.h>
#include <lasso/xml/id-wsf-2.0/subsref_create_item.h>
#include <lasso/xml/id-wsf-2.0/subsref_modify_item.h>
#include <lasso/xml/id-wsf-2.0/subsref_item_data.h>
#include <lasso/xml/id-wsf-2.0/subsref_data.h>
#include <lasso/xml/id-wsf-2.0/subs_notification.h>
#include <lasso/xml/id-wsf-2.0/ps_notification.h>
#include <lasso/xml/id-wsf-2.0/subsref_notification.h>
#include <lasso/xml/id-wsf-2.0/subs_ref_item.h>
#include <lasso/xml/id-wsf-2.0/subs_subscription.h>
#include <lasso/xml/id-wsf-2.0/subsref_subscription.h>
#include <lasso/xml/id-wsf-2.0/sb2_endpoint_update.h>
#include <lasso/xml/id-wsf-2.0/dst_result_query_base.h>
#include <lasso/xml/id-wsf-2.0/subsref_result_query.h>
#include <lasso/xml/id-wsf-2.0/subsref_query_item.h>
#include <lasso/xml/id-wsf-2.0/dst_request.h>
#include <lasso/xml/id-wsf-2.0/subsref_create.h>
#include <lasso/xml/id-wsf-2.0/subsref_modify.h>
#include <lasso/xml/id-wsf-2.0/subsref_delete.h>
#include <lasso/xml/id-wsf-2.0/subsref_notify.h>
#include <lasso/xml/id-wsf-2.0/subsref_query.h>
#include <lasso/xml/id-wsf-2.0/dst_delete_item_base.h>
#include <lasso/xml/id-wsf-2.0/subsref_delete_item.h>
#include <lasso/xml/id-wsf-2.0/dst_test_item_base.h>
#include <lasso/xml/id-wsf-2.0/subsref_test_item.h>
#include <lasso/xml/id-wsf-2.0/disco_endpoint_context.h>
#include <lasso/xml/id-wsf-2.0/disco_svc_md_replace.h>
#include <lasso/xml/id-wsf-2.0/disco_svc_md_query.h>
#include <lasso/xml/id-wsf-2.0/disco_keys.h>
#include <lasso/xml/id-wsf-2.0/disco_svc_metadata.h>
#include <lasso/xml/id-wsf-2.0/disco_options.h>
#include <lasso/xml/id-wsf-2.0/disco_provider_id.h>
#include <lasso/xml/id-wsf-2.0/disco_security_context.h>
#include <lasso/xml/id-wsf-2.0/disco_svc_md_replace_response.h>
#include <lasso/xml/id-wsf-2.0/disco_svc_md_delete.h>
#include <lasso/xml/id-wsf-2.0/disco_service_type.h>
#include <lasso/xml/id-wsf-2.0/disco_svc_md_register.h>
#include <lasso/xml/id-wsf-2.0/disco_svc_md_association_delete_response.h>
#include <lasso/xml/id-wsf-2.0/disco_svc_md_association_add.h>
#include <lasso/xml/id-wsf-2.0/disco_svc_md_register_response.h>
#include <lasso/xml/id-wsf-2.0/disco_requested_service.h>
#include <lasso/xml/id-wsf-2.0/disco_svc_md_association_query.h>
#include <lasso/xml/id-wsf-2.0/disco_svc_md_association_delete.h>
#include <lasso/xml/id-wsf-2.0/disco_svc_md_association_add_response.h>
#include <lasso/xml/id-wsf-2.0/disco_svc_md_association_query_response.h>
#include <lasso/xml/id-wsf-2.0/disco_svc_md_delete_response.h>
#include <lasso/xml/id-wsf-2.0/disco_svc_md_query_response.h>
#include <lasso/xml/id-wsf-2.0/disco_abstract.h>
#include <lasso/xml/id-wsf-2.0/disco_service_context.h>
#include <lasso/xml/id-wsf-2.0/disco_query.h>
#include <lasso/xml/id-wsf-2.0/disco_query_response.h>
#include <lasso/xml/id-wsf-2.0/util_status.h>
#include <lasso/xml/id-wsf-2.0/util_extension.h>
#include <lasso/xml/id-wsf-2.0/util_response.h>
#include <lasso/xml/id-wsf-2.0/subsref_delete_response.h>
#include <lasso/xml/id-wsf-2.0/subs_notify_response.h>
#include <lasso/xml/id-wsf-2.0/subsref_notify_response.h>
#include <lasso/xml/id-wsf-2.0/dst_delete_response.h>
#include <lasso/xml/id-wsf-2.0/dst_data_response_base.h>
#include <lasso/xml/id-wsf-2.0/subsref_data_response.h>
#include <lasso/xml/id-wsf-2.0/subsref_modify_response.h>
#include <lasso/xml/id-wsf-2.0/subsref_create_response.h>
#include <lasso/xml/id-wsf-2.0/subsref_query_response.h>
#include <lasso/xml/id-wsf-2.0/util_empty.h>
#include <lasso/xml/id-wsf-2.0/ims_mapping_output.h>
#include <lasso/xml/id-wsf-2.0/ims_identity_mapping_request.h>
#include <lasso/xml/id-wsf-2.0/ims_mapping_input.h>
#include <lasso/xml/id-wsf-2.0/ps_resolve_input.h>
#include <lasso/xml/id-wsf-2.0/ims_identity_mapping_response.h>
#include <lasso/xml/id-wsf-2.0/sec_transited_provider_path.h>
#include <lasso/xml/id-wsf-2.0/sec_token.h>
#include <lasso/xml/id-wsf-2.0/sec_token_policy.h>
#include <lasso/xml/id-wsf-2.0/sbf_framework.h>
#include <lasso/xml/id-wsf-2.0/dstref_data_response.h>
#include <lasso/xml/id-wsf-2.0/dstref_delete_response.h>
#include <lasso/xml/id-wsf-2.0/dstref_modify_item.h>
#include <lasso/xml/id-wsf-2.0/dstref_app_data.h>
#include <lasso/xml/id-wsf-2.0/dstref_test_item.h>
#include <lasso/xml/id-wsf-2.0/dstref_create.h>
#include <lasso/xml/id-wsf-2.0/dstref_item_data.h>
#include <lasso/xml/id-wsf-2.0/dstref_data.h>
#include <lasso/xml/id-wsf-2.0/dstref_modify.h>
#include <lasso/xml/id-wsf-2.0/dstref_result_query.h>
#include <lasso/xml/id-wsf-2.0/dstref_query_item.h>
#include <lasso/xml/id-wsf-2.0/dstref_create_response.h>
#include <lasso/xml/id-wsf-2.0/dstref_create_item.h>
#include <lasso/xml/id-wsf-2.0/dstref_query.h>
#include <lasso/xml/id-wsf-2.0/dstref_delete.h>
#include <lasso/xml/id-wsf-2.0/dstref_query_response.h>
#include <lasso/xml/id-wsf-2.0/dstref_delete_item.h>
#include <lasso/xml/id-wsf-2.0/dstref_modify_response.h>
#include <lasso/xml/id-wsf-2.0/is_interaction_statement.h>
#include <lasso/xml/id-wsf-2.0/is_help.h>
#include <lasso/xml/id-wsf-2.0/is_inquiry_element.h>
#include <lasso/xml/id-wsf-2.0/is_text.h>
#include <lasso/xml/id-wsf-2.0/is_interaction_response.h>
#include <lasso/xml/id-wsf-2.0/is_interaction_request.h>
#include <lasso/xml/id-wsf-2.0/is_item.h>
#include <lasso/xml/id-wsf-2.0/is_inquiry.h>
#include <lasso/xml/id-wsf-2.0/is_parameter.h>
#include <lasso/xml/id-wsf-2.0/is_select.h>
%}
%include sb2_sender.i
%include sb2_consent.i
%include sb2_redirect_request.i
%include sb2_user_interaction_header.i
%include sb2_usage_directive.i
%include sb2_target_identity.i
%include sb2_timeout.i
%include sb2_credentials_context.i
%include ps_object.i
%include ps_request_abstract.i
%include ps_test_membership_request.i
%include ps_remove_entity_request.i
%include ps_add_to_collection_request.i
%include ps_remove_collection_request.i
%include ps_add_known_entity_request.i
%include ps_add_entity_request.i
%include ps_remove_from_collection_request.i
%include ps_list_members_request.i
%include ps_query_objects_request.i
%include ps_set_object_info_request.i
%include ps_get_object_info_request.i
%include ps_item_data.i
%include ps_response_abstract.i
%include ps_add_known_entity_response.i
%include ps_add_entity_response.i
%include ps_add_collection_response.i
%include ps_query_objects_response.i
%include ps_list_members_response.i
%include ps_get_object_info_response.i
%include ps_resolve_identifier_response.i
%include ps_resolve_identifier_request.i
%include ps_test_membership_response.i
%include ps_add_collection_request.i
%include ps_notify.i
%include subsref_app_data.i
%include subsref_create_item.i
%include subsref_modify_item.i
%include subsref_item_data.i
%include subsref_data.i
%include subs_notification.i
%include ps_notification.i
%include subsref_notification.i
%include subs_ref_item.i
%include subs_subscription.i
%include subsref_subscription.i
%include sb2_endpoint_update.i
%include dst_result_query_base.i
%include subsref_result_query.i
%include subsref_query_item.i
%include dst_request.i
%include subsref_create.i
%include subsref_modify.i
%include subsref_delete.i
%include subsref_notify.i
%include subsref_query.i
%include dst_delete_item_base.i
%include subsref_delete_item.i
%include dst_test_item_base.i
%include subsref_test_item.i
%include disco_endpoint_context.i
%include disco_svc_md_replace.i
%include disco_svc_md_query.i
%include disco_keys.i
%include disco_svc_metadata.i
%include disco_options.i
%include disco_provider_id.i
%include disco_security_context.i
%include disco_svc_md_replace_response.i
%include disco_svc_md_delete.i
%include disco_service_type.i
%include disco_svc_md_register.i
%include disco_svc_md_association_delete_response.i
%include disco_svc_md_association_add.i
%include disco_svc_md_register_response.i
%include disco_requested_service.i
%include disco_svc_md_association_query.i
%include disco_svc_md_association_delete.i
%include disco_svc_md_association_add_response.i
%include disco_svc_md_association_query_response.i
%include disco_svc_md_delete_response.i
%include disco_svc_md_query_response.i
%include disco_abstract.i
%include disco_service_context.i
%include disco_query.i
%include disco_query_response.i
%include util_status.i
%include util_extension.i
%include util_response.i
%include subsref_delete_response.i
%include subs_notify_response.i
%include subsref_notify_response.i
%include dst_delete_response.i
%include dst_data_response_base.i
%include subsref_data_response.i
%include subsref_modify_response.i
%include subsref_create_response.i
%include subsref_query_response.i
%include util_empty.i
%include ims_mapping_output.i
%include ims_identity_mapping_request.i
%include ims_mapping_input.i
%include ps_resolve_input.i
%include ims_identity_mapping_response.i
%include sec_transited_provider_path.i
%include sec_token.i
%include sec_token_policy.i
%include sbf_framework.i
%include dstref_data_response.i
%include dstref_delete_response.i
%include dstref_modify_item.i
%include dstref_app_data.i
%include dstref_test_item.i
%include dstref_create.i
%include dstref_item_data.i
%include dstref_data.i
%include dstref_modify.i
%include dstref_result_query.i
%include dstref_query_item.i
%include dstref_create_response.i
%include dstref_create_item.i
%include dstref_query.i
%include dstref_delete.i
%include dstref_query_response.i
%include dstref_delete_item.i
%include dstref_modify_response.i
%include is_interaction_statement.i
%include is_help.i
%include is_inquiry_element.i
%include is_text.i
%include is_interaction_response.i
%include is_interaction_request.i
%include is_item.i
%include is_inquiry.i
%include is_parameter.i
%include is_select.i