SET_NODE_INFO(WsUtil1Timestamp, Node)
SET_NODE_INFO(WsAddrProblemAction, Node)
SET_NODE_INFO(WsAddrRelatesTo, Node)
SET_NODE_INFO(WsAddrAttributedURI, Node)
SET_NODE_INFO(WsAddrAttributedUnsignedLong, Node)
SET_NODE_INFO(WsAddrAttributedQName, Node)
SET_NODE_INFO(WsAddrReferenceParameters, Node)
SET_NODE_INFO(WsAddrEndpointReference, Node)
SET_NODE_INFO(WsAddrAttributedAny, Node)
SET_NODE_INFO(WsAddrMetadata, Node)
SET_NODE_INFO(WsSec1SecurityHeader, Node)
SET_NODE_INFO(WsSec1Reference, Node)
SET_NODE_INFO(WsSec1Embedded, Node)
SET_NODE_INFO(WsSec1UsernameToken, Node)
SET_NODE_INFO(WsSec1TransformationParameters, Node)
SET_NODE_INFO(WsSec1SecurityTokenReference, Node)

