#define LASSO_SAML2_SUPPORT 1

/* NameIdPolicy */
#ifndef SWIGPHP4
%rename(SAML2_NAME_IDENTIFIER_FORMAT_PERSISTENT) LASSO_SAML2_NAME_IDENTIFIER_FORMAT_PERSISTENT;
%rename(SAML2_NAME_IDENTIFIER_FORMAT_TRANSIENT) LASSO_SAML2_NAME_IDENTIFIER_FORMAT_TRANSIENT;
#endif
#define LASSO_SAML2_NAME_IDENTIFIER_FORMAT_PERSISTENT \
		"urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"
#define LASSO_SAML2_NAME_IDENTIFIER_FORMAT_TRANSIENT \
		"urn:oasis:names:tc:SAML:2.0:nameid-format:transient"

/* AuthnClassRef */
#ifndef SWIGPHP4
%rename(SAML2_AUTHN_CONTEXT_AUTHENTICATED_TELEPHONY) \
	LASSO_SAML2_AUTHN_CONTEXT_AUTHENTICATED_TELEPHONY;
%rename(SAML2_AUTHN_CONTEXT_INTERNET_PROTOCOL) \
	LASSO_SAML2_AUTHN_CONTEXT_INTERNET_PROTOCOL;
%rename(SAML2_AUTHN_CONTEXT_INTERNET_PROTOCOL_PASSWORD) \
	LASSO_SAML2_AUTHN_CONTEXT_INTERNET_PROTOCOL_PASSWORD;
%rename(SAML2_AUTHN_CONTEXT_KERBEROS) \
	LASSO_SAML2_AUTHN_CONTEXT_KERBEROS;
%rename(SAML2_AUTHN_CONTEXT_MOBILE_ONE_FACTOR_CONTRACT) \
	LASSO_SAML2_AUTHN_CONTEXT_MOBILE_ONE_FACTOR_CONTRACT;
%rename(SAML2_AUTHN_CONTEXT_MOBILE_ONE_FACTOR_UNREGISTERED) \
	LASSO_SAML2_AUTHN_CONTEXT_MOBILE_ONE_FACTOR_UNREGISTERED;
%rename(SAML2_AUTHN_CONTEXT_MOBILE_TWO_FACTOR_CONTRACT) \
	LASSO_SAML2_AUTHN_CONTEXT_MOBILE_TWO_FACTOR_CONTRACT;
%rename(SAML2_AUTHN_CONTEXT_MOBILE_TWO_FACTOR_UNREGISTERED) \
	LASSO_SAML2_AUTHN_CONTEXT_MOBILE_TWO_FACTOR_UNREGISTERED;
%rename(SAML2_AUTHN_CONTEXT_NOMAD_TELEPHONY) \
	LASSO_SAML2_AUTHN_CONTEXT_NOMAD_TELEPHONY;
%rename(SAML2_AUTHN_CONTEXT_PERSONALIZED_TELEPHONY) \
	LASSO_SAML2_AUTHN_CONTEXT_PERSONALIZED_TELEPHONY;
%rename(SAML2_AUTHN_CONTEXT_PGP) \
	LASSO_SAML2_AUTHN_CONTEXT_PGP;
%rename(SAML2_AUTHN_CONTEXT_PASSWORD_PROTECTED_TRANSPORT) \
	LASSO_SAML2_AUTHN_CONTEXT_PASSWORD_PROTECTED_TRANSPORT;
%rename(SAML2_AUTHN_CONTEXT_PASSWORD) \
	LASSO_SAML2_AUTHN_CONTEXT_PASSWORD;
%rename(SAML2_AUTHN_CONTEXT_PREVIOUS_SESSION) \
	LASSO_SAML2_AUTHN_CONTEXT_PREVIOUS_SESSION;
%rename(SAML2_AUTHN_CONTEXT_SMARTCARD) \
	LASSO_SAML2_AUTHN_CONTEXT_SMARTCARD;
%rename(SAML2_AUTHN_CONTEXT_SMARTCARD_PKI) \
	LASSO_SAML2_AUTHN_CONTEXT_SMARTCARD_PKI;
%rename(SAML2_AUTHN_CONTEXT_SOFTWARE_PKI) \
	LASSO_SAML2_AUTHN_CONTEXT_SOFTWARE_PKI;
%rename(SAML2_AUTHN_CONTEXT_SPKI) \
	LASSO_SAML2_AUTHN_CONTEXT_SPKI;
%rename(SAML2_AUTHN_CONTEXT_SECURE_REMOTE_PASSWORD) \
	LASSO_SAML2_AUTHN_CONTEXT_SECURE_REMOTE_PASSWORD;
%rename(SAML2_AUTHN_CONTEXT_TLS_CLIENT) \
	LASSO_SAML2_AUTHN_CONTEXT_TLS_CLIENT;
%rename(SAML2_AUTHN_CONTEXT_X509) \
	LASSO_SAML2_AUTHN_CONTEXT_X509;
%rename(SAML2_AUTHN_CONTEXT_TELEPHONY) \
	LASSO_SAML2_AUTHN_CONTEXT_TELEPHONY;
%rename(SAML2_AUTHN_CONTEXT_TIME_SYNC_TOKEN) \
	LASSO_SAML2_AUTHN_CONTEXT_TIME_SYNC_TOKEN;
%rename(SAML2_AUTHN_CONTEXT_XMLDSIG) \
	LASSO_SAML2_AUTHN_CONTEXT_XMLDSIG;
#endif
#define LASSO_SAML2_AUTHN_CONTEXT_AUTHENTICATED_TELEPHONY \
	"urn:oasis:names:tc:SAML:2.0:ac:classes:AuthenticatedTelephony"
#define LASSO_SAML2_AUTHN_CONTEXT_INTERNET_PROTOCOL \
	"urn:oasis:names:tc:SAML:2.0:ac:classes:InternetProtocol"
#define LASSO_SAML2_AUTHN_CONTEXT_INTERNET_PROTOCOL_PASSWORD \
	"urn:oasis:names:tc:SAML:2.0:ac:classes:InternetProtocolPassword"
#define LASSO_SAML2_AUTHN_CONTEXT_KERBEROS \
	"urn:oasis:names:tc:SAML:2.0:ac:classes:Kerberos"
#define LASSO_SAML2_AUTHN_CONTEXT_MOBILE_ONE_FACTOR_CONTRACT \
	"urn:oasis:names:tc:SAML:2.0:ac:classes:MobileOneFactorContract"
#define LASSO_SAML2_AUTHN_CONTEXT_MOBILE_ONE_FACTOR_UNREGISTERED \
	"urn:oasis:names:tc:SAML:2.0:ac:classes:MobileOneFactorUnregistered"
#define LASSO_SAML2_AUTHN_CONTEXT_MOBILE_TWO_FACTOR_CONTRACT \
	"urn:oasis:names:tc:SAML:2.0:ac:classes:MobileTwoFactorContract"
#define LASSO_SAML2_AUTHN_CONTEXT_MOBILE_TWO_FACTOR_UNREGISTERED \
	"urn:oasis:names:tc:SAML:2.0:ac:classes:MobileTwoFactorUnregistered"
#define LASSO_SAML2_AUTHN_CONTEXT_NOMAD_TELEPHONY \
	"urn:oasis:names:tc:SAML:2.0:ac:classes:NomadTelephony"
#define LASSO_SAML2_AUTHN_CONTEXT_PERSONALIZED_TELEPHONY \
	"urn:oasis:names:tc:SAML:2.0:ac:classes:PersonalizedTelephony"
#define LASSO_SAML2_AUTHN_CONTEXT_PGP \
	"urn:oasis:names:tc:SAML:2.0:ac:classes:PGP"
#define LASSO_SAML2_AUTHN_CONTEXT_PASSWORD_PROTECTED_TRANSPORT \
	"urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport"
#define LASSO_SAML2_AUTHN_CONTEXT_PASSWORD \
	"urn:oasis:names:tc:SAML:2.0:ac:classes:Password"
#define LASSO_SAML2_AUTHN_CONTEXT_PREVIOUS_SESSION \
	"urn:oasis:names:tc:SAML:2.0:ac:classes:PreviousSession"
#define LASSO_SAML2_AUTHN_CONTEXT_SMARTCARD \
	"urn:oasis:names:tc:SAML:2.0:ac:classes:Smartcard"
#define LASSO_SAML2_AUTHN_CONTEXT_SMARTCARD_PKI \
	"urn:oasis:names:tc:SAML:2.0:ac:classes:SmartcardPKI"
#define LASSO_SAML2_AUTHN_CONTEXT_SOFTWARE_PKI \
	"urn:oasis:names:tc:SAML:2.0:ac:classes:SoftwarePKI"
#define LASSO_SAML2_AUTHN_CONTEXT_SPKI \
	"urn:oasis:names:tc:SAML:2.0:ac:classes:SPKI"
#define LASSO_SAML2_AUTHN_CONTEXT_SECURE_REMOTE_PASSWORD \
	"urn:oasis:names:tc:SAML:2.0:ac:classes:SecureRemotePassword"
#define LASSO_SAML2_AUTHN_CONTEXT_TLS_CLIENT \
	"urn:oasis:names:tc:SAML:2.0:ac:classes:TLSClient"
#define LASSO_SAML2_AUTHN_CONTEXT_X509 \
	"urn:oasis:names:tc:SAML:2.0:ac:classes:X509"
#define LASSO_SAML2_AUTHN_CONTEXT_TELEPHONY \
	"urn:oasis:names:tc:SAML:2.0:ac:classes:Telephony"
#define LASSO_SAML2_AUTHN_CONTEXT_TIME_SYNC_TOKEN \
	"urn:oasis:names:tc:SAML:2.0:ac:classes:TimeSyncToken"
#define LASSO_SAML2_AUTHN_CONTEXT_XMLDSIG \
	"urn:oasis:names:tc:SAML:2.0:ac:classes:XMLDSig"


