#! /usr/bin/env python

import glob
import re

fd = open('types.c', 'w')

print >> fd, "/* This file has been autogenerated; changes will be lost */"
print >> fd, ""
print >> fd, "typedef GType (*type_function) (void);"
print >> fd, ""

for header_file in glob.glob('*/*.h'):
    try:
        type = re.findall('lasso_.*get_type', open(header_file).read())[0]
    except IndexError:
        continue
    print >> fd, "extern GType %s();" % type

print >> fd, ""
print >> fd, "type_function functions[] = {"
for header_file in glob.glob('*/*.h'):
    try:
        type = re.findall('lasso_.*get_type', open(header_file).read())[0]
    except IndexError:
        continue
    print >> fd, "\t%s," % type
print >> fd, "\tNULL"
print >> fd, "};"

