%{
#include <lasso/xml/ws/wsu_timestamp.h>
#include <lasso/xml/ws/wsa_problem_action.h>
#include <lasso/xml/ws/wsa_relates_to.h>
#include <lasso/xml/ws/wsa_attributed_uri.h>
#include <lasso/xml/ws/wsa_attributed_unsigned_long.h>
#include <lasso/xml/ws/wsa_attributed_qname.h>
#include <lasso/xml/ws/wsa_reference_parameters.h>
#include <lasso/xml/ws/wsa_endpoint_reference.h>
#include <lasso/xml/ws/wsa_attributed_any.h>
#include <lasso/xml/ws/wsa_metadata.h>
#include <lasso/xml/ws/wsse_security_header.h>
#include <lasso/xml/ws/wsse_reference.h>
#include <lasso/xml/ws/wsse_embedded.h>
#include <lasso/xml/ws/wsse_username_token.h>
#include <lasso/xml/ws/wsse_transformation_parameters.h>
#include <lasso/xml/ws/wsse_security_token_reference.h>
%}
%include wsu_timestamp.i
%include wsa_problem_action.i
%include wsa_relates_to.i
%include wsa_attributed_uri.i
%include wsa_attributed_unsigned_long.i
%include wsa_attributed_qname.i
%include wsa_reference_parameters.i
%include wsa_endpoint_reference.i
%include wsa_attributed_any.i
%include wsa_metadata.i
%include wsse_security_header.i
%include wsse_reference.i
%include wsse_embedded.i
%include wsse_username_token.i
%include wsse_transformation_parameters.i
%include wsse_security_token_reference.i